CREATE TABLE users (
  id SERIAL PRIMARY KEY,
  email TEXT UNIQUE NOT NULL,
  totp_secret TEXT
);

CREATE TABLE um (
    cod TEXT PRIMARY KEY,
    descrizione TEXT UNIQUE
);

INSERT INTO public.um (cod, descrizione) VALUES
('PZ', 'Pezzi'),
('KG', 'Kilogrammi'),
('LT', 'Litri'),
('MT', 'Metri');

CREATE TABLE scrap (
    cod TEXT PRIMARY KEY,
    descrizione TEXT UNIQUE
);

INSERT INTO public.scrap (cod, descrizione) VALUES
('SC1', 'Causale 1'),
('SC2', 'Causale 2'),
('SC3', 'Causale 3'),
('SC4', 'Causale 4');

CREATE TABLE wc (
    cod TEXT PRIMARY KEY,
    descrizione TEXT UNIQUE
);

INSERT INTO public.wc (cod, descrizione) VALUES
('WC1', 'Work center 1'),
('WC2', 'Work center 2'),
('WC3', 'Work center 3'),
('WC4', 'Work center 4');

CREATE TABLE prod (
    id                INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    odp               TEXT NOT NULL,
    operatore         TEXT,
    wc                TEXT REFERENCES wc(cod),
    fase              TEXT,
    prodotto          TEXT NOT NULL,
    um_prod           TEXT REFERENCES um(cod),
    qta_prodotta      NUMERIC(15,3),
    hu_prod_ok        TEXT,
    nr_fili           NUMERIC(15,3),
    qta_scartata      NUMERIC(15,3),
    hu_scarto         TEXT,
    cod_scarto        TEXT REFERENCES scrap(cod),
    data_ora_inizio   TIMESTAMP,
    data_ora_fine     TIMESTAMP,
    componente        TEXT,
    hu_comp           TEXT,
    flag_hu_comp      CHAR(1) DEFAULT 'N'
                      CHECK (flag_hu_comp IN ('Y','N')),
    um_cons           TEXT REFERENCES um(cod),
    qta_cons          NUMERIC(15,3),
    hold              BOOLEAN DEFAULT(false)
);

CREATE OR REPLACE FUNCTION enforce_uppercase()
RETURNS TRIGGER AS $$
BEGIN
    NEW.odp := UPPER(NEW.odp);
    NEW.prodotto := UPPER(NEW.prodotto);
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_uppercase
BEFORE INSERT OR UPDATE ON prod
FOR EACH ROW
EXECUTE FUNCTION enforce_uppercase();
